# Generated by Django 3.2.8 on 2021-11-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='teachers/teacher.jpg', upload_to='teachers/%Y/%m/%d/'),
        ),
    ]
