# Generated by Django 3.2.8 on 2021-10-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/default.png', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
